# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in RakeFile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{visitor_sources}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matt Fawcett"]
  s.date = %q{2010-03-05}
  s.description = %q{Use a cookie to record the sources that each visitor came to your site}
  s.email = %q{mail@matthewfawcett.co.uk}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
     "VERSION",
     "lib/visitor_sources.rb",
     "lib/visitor_sources/search_engine.rb",
     "lib/visitor_sources/traffic_source.rb",
     "lib/visitor_sources/traffic_source_middleware.rb",
     "lib/visitor_sources/traffic_sources.rb",
     "test/app.rb",
     "test/search_engine_test.rb",
     "test/test_helper.rb",
     "test/traffic_source_middleware_test.rb",
     "test/traffic_source_test.rb",
     "test/traffic_sources_test.rb"
  ]
  s.homepage = %q{http://github.com/mattfawcett/visitor_sources}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Use a cookie to record the sources that each visitor came to your site}
  s.test_files = [
    "test/app.rb",
     "test/search_engine_test.rb",
     "test/test_helper.rb",
     "test/traffic_source_middleware_test.rb",
     "test/traffic_source_test.rb",
     "test/traffic_sources_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

